language: objective-c
osx_image: xcode7.3
script:
- xcodebuild clean test -workspace Furni.xcworkspace -scheme "Furni" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
