language: objective-c
osx_image: xcode7
script:
    - "xctool -workspace Furni.xcworkspace -scheme Furni -sdk iphonesimulator9.1 -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.1' build test"
